name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: mackerel-agent
          - package: minio-modified
          - package: nginx-mainline-mod-brotli
          - package: nginx-mainline-mod-fancyindex
          - package: nginx-mainline-mod-headers-more
          - package: openarc
          - package: otelcol
    steps:
      - uses: actions/checkout@v4

      - name: Check eligibility
        env:
          GH_TOKEN: ${{ secrets._GITHUB_TOKEN }}
        run: |
          _PACKAGE=${{ matrix.package }}
          _PACKAGE=${_PACKAGE^^}
          _PREVIOUS_PKGVER=$(gh variable get ${_PACKAGE//-/_}_PKGVER)
          echo "_PREVIOUS_PKGVER=$_PREVIOUS_PKGVER" >> $GITHUB_ENV
          cd ${{ matrix.package }}
          _VER=$(cat .SRCINFO | grep "pkgver" | awk '{print $3}')
          _REL=$(cat .SRCINFO | grep "pkgrel" | awk '{print $3}')
          _PKGVER=$_VER-$_REL
          echo "_PKGVER=$_PKGVER" >> $GITHUB_ENV
          echo "Previous version: $_PREVIOUS_PKGVER"
          echo "Current version: $_PKGVER"

      - name: Set up Docker Buildx
        if: ${{ env._PKGVER != env._PREVIOUS_PKGVER }}
        uses: docker/setup-buildx-action@v3

      - name: Build
        if: ${{ env._PKGVER != env._PREVIOUS_PKGVER }}
        run: |
          cd ${{ matrix.package }}
          cp ../Dockerfile .
          docker build -t dist .

      - name: Export
        if: ${{ env._PKGVER != env._PREVIOUS_PKGVER }}
        run: docker run -v "./dist:/opt/builder/dist" --user root --rm dist sh -c "cp *.pkg.tar.zst dist"

      - name: Upload artifact
        if: ${{ env._PKGVER != env._PREVIOUS_PKGVER }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}
          path: ./dist/*.pkg.tar.zst

      - name: Update current commit
        if: ${{ env._PKGVER != env._PREVIOUS_PKGVER }}
        env:
          GH_TOKEN: ${{ secrets._GITHUB_TOKEN }}
        run: |
          _PACKAGE=${{ matrix.package }}
          _PACKAGE=${_PACKAGE^^}
          gh variable set ${_PACKAGE//-/_}_PKGVER --body $_PKGVER

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Prepare artifact
        uses: actions/download-artifact@v4

      - name: Check eligibility
        run: echo "_PACKAGES_COUNT=$(ls | wc -l)" >> $GITHUB_ENV

      - name: Upload packages
        if: ${{ env._PACKAGES_COUNT > 0 }}
        env:
          _TOKEN: ${{ secrets._TOKEN }}
        run: |
          mkdir dist
          cp */*.pkg.tar.zst dist
          cd dist
          ls -l
          tar -cf ../build.tar.gz *.pkg.tar.zst
          cd ..
          curl -H "X-Token:$_TOKEN" -H "X-Repo:pkgbuilds" -F build=@build.tar.gz https://gomasy.jp/api/v1/github/push
